stash

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25,7 +25,7 @@ init () {
 
     web_assets_deps="lessc coffee handlebars browserify proto2js"
     npm_deps="$web_assets_deps"
-    required_bin_deps="protoc $web_assets_deps"
+    required_bin_deps="protoc"
     optional_bin_deps="wget curl"
     bin_deps="cxx $npm_deps $required_bin_deps $optional_bin_deps"
     all_deps="$bin_deps $all_libs"
@@ -37,6 +37,7 @@ init () {
 configure () {
     require "Bash"
     show "$BASH_VERSION"
+    var FETCH_LIST ""
     for var in $allowed_arg_vars; do
         local val
         if lookup "$arg_vars" $var val; then
@@ -102,7 +103,7 @@ configure () {
         optional_dep $bin
         check_bin $bin
     done
-    if any "$fetch_list" contains "$npm_deps"; then
+    if any "$FETCH_LIST" contains "$npm_deps"; then
         require_dep npm
         check_bin npm
     fi
@@ -113,7 +114,7 @@ configure () {
     check_v8_pre_3_19
     if [[ $NO_TCMALLOC = 0 ]] ; then
         check_lib tcmalloc_minimal
-        if contains "$fetch_list" tcmalloc_minimal; then
+        if contains "$FETCH_LIST" tcmalloc_minimal; then
             check_lib unwind
         fi
     else
@@ -122,8 +123,7 @@ configure () {
     test_protobuf
     check_boost
     boolvar STATIC_V8 contains "$static_libs" v8
-    var FETCH_LIST "$fetch_list"
-    boolvar FETCH_INTERNAL_TOOLS $allow_fetch
+    boolvar ALLOW_FETCH $allow_fetch
     require Installation prefix
     var PREFIX ${arg_prefix:-/usr/local}
     require Configuration prefix
@@ -675,30 +675,38 @@ check_bin () {
     var "$(uc $1)_DEP" ""
 }
 
-# List of dependencies that make will fetch
-fetch_list=
-
-# fetch_bin <name>
-# Instruct make to fetch and build the binary
-fetch_bin () {
-    error "TODO: fetch_bin"
-    return 1
-    show fetch
-    macro $(uc $1) "\$(FETCH_PREFIX)/bin/$(lc $1)"
-    var $(uc $1)_DEP "\$(FETCH_PREFIX)/bin/$(lc $1)"
-    fetch_list="$fetch_list $1"
+# add_fetch <name>
+# Instruct make to fetch and build the dependency
+# Sets the pkg and version variables
+add_fetch () {
+    pkg=$(pkg_name "$1")
+    if ! version=$(bash $root/support/pkg/pkg.sh "$pkg" version); then
+        error "Internal error: cannot fetch $pkg"
+        return 1
+    fi
+    show fetch $pkg-$version
+    if ! contains "$FETCH_LIST" "$pkg"; then
+        var_append FETCH_LIST "$1"
+    fi
 }
 
-# fetch_lib <name>
-# Instruct make to fetch and build the library
+# Chose to fetch the given binary
+fetch_bin () {
+    local pkg
+    local version
+    add_fetch "$1"
+    macro "$1"     "\$(SUPPORT_BUILD_DIR)/$pkg-$version/bin/$1"
+    macro "$1_DEP" "\$(SUPPORT_BUILD_DIR)/$pkg-$version/bin/$1"
+}
+
+# Chose to fetch the given library
 fetch_lib () {
-    error "TODO: fetch_lib"
-    return 1
-    show fetch
-    local lib="\$(FETCH_PREFIX)/lib/lib$(lc $1).a"
-    var $(uc $1)_DEP "$lib"
-    var_append $(uc $1)_LIBS "$lib"
-    fetch_list="$fetch_list $1"
+    local pkg
+    local version
+    add_fetch "$1"
+    macro "$1_LIBS"    "\$(SUPPORT_BUILD_DIR)/$pkg-$version/lib/$1.a"
+    macro "$1_LD_DEP"  "\$(SUPPORT_BUILD_DIR)/$pkg-$version/lib/$1.a"
+    macro "$1_CXX_DEP" "\$(SUPPORT_BUILD_DIR)/$pkg-$version/include"
 }
 
 # require_dep <name>
@@ -791,7 +799,6 @@ check_lib () {
 }
 
 check_dyn_lib () {
-    # TODO: pkg_config
     check_lib_compile -l$1 $2
 }
 
@@ -804,14 +811,14 @@ check_lib_compile () {
     fi
     echo "$code" > "$bfile.cc"
     if "$CXX" ${CXXFLAGS:-} ${LDFLAGS:-} ${LIB_SEARCH_PATHS:-} "$bfile.cc" $1 -o "$bfile.out" 1>"$bfile.log" 2>&1; then
-	var_append $(uc $2)_LIBS ${1:-yes}
+        show "${1:-ok}"
+	var_append $(uc $2)_LIBS "$1"
     else
         error_details="${error_details:-}"$(cat "$bfile.log")
     fi
 }
 
 check_static_lib () {
-    # TODO: pkg-config
     local path=$(static_lib_lookup $1)
     if [[ -n "$path" ]]; then
         var_append $(uc $2)_LIBS "$path"
@@ -854,9 +861,10 @@ niceabspath () {
     fi
 }
 
+# Test that PROTOC and PROTOBUF_LIBS work together
 test_protobuf () {
     require "Test protobuf"
-    if any "protoc protobuf" contains "$fetch_list"; then
+    if any "protoc protobuf" contains "$FETCH_LIST"; then
         show fetch
         return
     fi
@@ -881,13 +889,16 @@ test_protobuf () {
     show ok
 }
 
+# fetch_allowed <dep>
+# Fails if the dependency cannot be fetched
 fetch_allowed () {
-     (contains "$please_fetch_list" $1 ||
-         (can_fetch $1 && $allow_fetch)) || return 1
+     { contains "$please_fetch_list" $1 ||
+         { can_fetch $1 && $allow_fetch ; } ; } || return 1
 }
 
+# Checks what version of the v8 API is available
 check_v8_pre_3_19 () {
-    if contains "$fetch_list" v8; then
+    if contains "$FETCH_LIST" v8; then
         boolvar V8_PRE_3_19 false
         return
     fi
@@ -912,23 +923,33 @@ EOF
     fi
 }
 
+# Check for boost
 check_boost () {
-    require "Boost"
+    require "Test boost"
     check_lib_compile "" boost
 }
 
-fetch_alias () {
+# pkg_name <dep>
+# The support package name that contains dep
+pkg_name () {
     case "$1" in
         protoc) echo protobuf ;;
+        tcmalloc_minimal) echo gperftools ;;
+        lessc) echo less ;;
+        coffee) echo coffee-script ;;
+        proto2js) echo protobufjs ;;
         *) echo "$1"
     esac
 }
 
+# can_fetch <dep>
+# Check if we know how to fetch dep
 can_fetch () {
-    local alias=$(fetch_alias $1)
-    test -e $root/support/specs/"$alias".sh
+    local pkg=$(pkg_name $1)
+    test -e $root/support/pkg/"$pkg".sh
 }
 
+# List all the packages that can be fetched
 all_fetch_deps () {
     local ret=
     for dep in $all_deps; do
@@ -939,6 +960,7 @@ all_fetch_deps () {
     echo "$ret"
 }
 
+# The root of the source tree
 root=$(dirname $0)
 
 # Call the main command with the command line arguments
